model_list:
  - model_name: grok-4-1-fast-reasoning
    litellm_params:
      model: xai/grok-4-1-fast-reasoning
      api_key: os.environ/XAI_API_KEY

  - model_name: gpt-5-mini
    litellm_params:
      model: openai/gpt-5-mini
      api_key: os.environ/OPENAI_API_KEY
      temperature: 1.0

  - model_name: kimi-2.5
    litellm_params:
      model: deepinfra/moonshotai/Kimi-K2.5
      api_key: os.environ/DEEPINFRA_API_KEY

litellm_settings:
  fallbacks: [{"grok-4-1-fast-reasoning": ["gpt-5-mini", "kimi-2.5"]}]